// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHwqcaoysg1qQrzk1lSoPfCS210tBjrE',
    appId: '1:472809901922:web:eba06b70be2addc7e1663b',
    messagingSenderId: '472809901922',
    projectId: 'reliableHands-farmer',
    authDomain: 'khaity-farmer.firebaseapp.com',
    storageBucket: 'khaity-farmer.appspot.com',
    measurementId: 'G-HJY4CDEQEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9FgPMGZcdWbQPphjZ1X3HW_wvQjNw7s',
    appId: '1:472809901922:android:f77e2e17420a4008e1663b',
    messagingSenderId: '472809901922',
    projectId: 'khaity-farmer',
    storageBucket: 'khaity-farmer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkSJx7VXE0oW0KVWjC3betTGF_x3HzuQ',
    appId: '1:472809901922:ios:f84970c328ad41f3e1663b',
    messagingSenderId: '472809901922',
    projectId: 'khaity-farmer',
    storageBucket: 'khaity-farmer.appspot.com',
    iosClientId: '472809901922-oqsf5o2mhq3qad5a50kpjuaiug7uelbq.apps.googleusercontent.com',
    iosBundleId: 'com.khaity.khaity',
  );
}
